# Generated by Django 4.0.5 on 2022-07-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='demo'),
            preserve_default=False,
        ),
    ]
