# Generated by Django 4.0.5 on 2022-07-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderitem_ordered_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
