# Generated by Django 4.0.5 on 2022-07-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_payment_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='demo', upload_to=''),
            preserve_default=False,
        ),
    ]
